Jyms Tonic pr prez for your pleasure
WolfyL/DesCallerKata--new pull request #3
Opened 2021-10-01 13:12 UTC by WolfyL

2021-10-01 13:12 UTC, MaximeSkello requested changes

2021-10-01 13:12 UTC, MaximeSkello commented on views/index.jade
> +    blbl Jyms Tonic prez
inadmissible

2021-10-01 13:15 UTC, MerciMax commented on views/index.jade
> +    blbl Jyms Tonic prez
up

2021-10-01 13:16 UTC, MaximeSkello commented
il serait préférable de rajouter une description dans cette requète d'ouverture afin de pouvoir comprendre le code merci.

2021-10-01 13:17 UTC, WolfyL commented on views/index.jade
> +    blbl Jyms Tonic prez
m'en fous

2021-10-01 14:05 UTC, MaximeSkello requested changes

2021-10-01 14:05 UTC, MaximeSkello commented on views/index.jade
> +    blbl Jyms Tonic prez
C'est quand meme pas compliqué fais un effort stp
```suggestion
    const blbl = 'blbl';
    const jyms = 'Jyms';
    const tonic = 'Tonic';
    const prez = 'prez';
    console.log(blbl, jyms, tonic, prez);
```

2021-10-02 10:10 UTC, YasmineFarhani approved these changes

2021-10-04 12:08 UTC, closed without merging